"""
Project Configuration

Author:
    Mrityunjay Dubey

Description:
    This module centralizes all configurable parameters used across the
    Retrieval-Augmented Generation (RAG) pipeline.

    No module should hardcode configurable values such as file paths,
    chunk size, overlap, retrieval parameters, etc.

    Any future changes should be made only in this file.
"""

from pathlib import Path

# ==============================================================================
# Project Directories
# ==============================================================================

# Project Root Directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Data Directories
DATA_DIR = PROJECT_ROOT / "data"

# Cleaned corpus from Assignment-1
CORPUS_DIR = DATA_DIR / "corpus"

# Stores intermediate artifacts generated by the pipeline
PROCESSED_DIR = DATA_DIR / "processed"

# Evaluation data
EVALUATION_DIR = DATA_DIR / "evaluation"

# Output Directory
OUTPUT_DIR = PROJECT_ROOT / "outputs"

# ==============================================================================
# Chunking Configuration
# ==============================================================================

# Maximum number of tokens allowed in a chunk
MAX_CHUNK_TOKENS = 200

# Number of tokens to overlap between consecutive chunks
CHUNK_OVERLAP_TOKEN_COUNT = 20

# ==============================================================================
# Retrieval Configuration
# ==============================================================================

# Number of documents to retrieve
TOP_K = 5

# ==============================================================================
# Logging Configuration
# ==============================================================================

LOG_LEVEL = "INFO"

# ==============================================================================
# Random Seed
# ==============================================================================

# Ensures reproducible results whenever randomness is involved
RANDOM_SEED = 42

# ==============================================================================
# Tokenizer Configuration
# ==============================================================================

TOKENIZER_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

TOKENIZER_DIRECTORY = (
    PROJECT_ROOT
    / "models"
    / "tokenizer"
    / "current"
)